# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

encoding: UTF-8
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: I can't remember where I read it...
repository: adrianbanks/adrianbanks.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: memory.Refresh()

description: Stylish Jekyll Theme
author:
  name: Adrian Banks
  github: adrianbanks
  twitter: adrianbanks  
  bio: An online collection of post-it notes
  email_md5: 6de17b18a71b8b65b7fddfce827f123f

rss_path: feed.xml
about_path: about.html
contact_path: contact.html
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: /assets/media/images/background.png

BASE_PATH:

gems:
  - jekyll-paginate
