# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

encoding: UTF-8
paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: UA-1997415-1
title: I can't remember where I read it...
repository: adrianbanks/adrianbanks.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: memory.Refresh()

description: An online collection of post-it notes
author:
  name: Adrian Banks
  github: adrianbanks
  twitter: adrianbanks
  mastodon: mastodon.social/@adrianbanks
  stackoverflow: 116923
  bio: An online collection of post-it notes
  email: websitecontact@adrianbanks.co.uk
  email_md5: 6de17b18a71b8b65b7fddfce827f123f

rss_path: feed.xml
about_path: about.html
contact_path: contact.html
categories_path: categories.html
tags_path: tags.html

sidebar_background_image: /assets/media/images/background.png

BASE_PATH: https://blog.adrianbanks.co.uk

plugins:
  - jekyll-paginate
