# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

encoding: UTF-8
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: I can't remember where I read it...
repository: adrianbanks/adrianbanks.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: memory.Jog()

description: Stylish Jekyll Theme
author:
  name: Adrian Banks
  email: contact@adrianbanks.co.uk
  github: adrianbanks
  twitter: adrianbanks  
  bio: An online collection of post-it notes
  email_md5: 6DE17B18A71B8B65B7FDDFCE827F123F

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
